name: GitHub Readme Stats

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate stats
        uses: anuraghazra/github-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Marques-Richard
          SHOW_ICONS: true
          THEME: tokyonight
          INCLUDE_ALL_COMMITS: true
          COUNT_PRIVATE: true
